const colors = {
  light: {
    text: '#0F172A',
    tint: '#2563EB',
    background: '#F8FAFC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#2563EB',
    primaryDark: '#1D4ED8',
    primaryLight: '#60A5FA',
    primaryForeground: '#FFFFFF',
    secondary: '#0F172A',
    secondaryForeground: '#FFFFFF',
    accent: '#10B981',
    accentForeground: '#FFFFFF',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    surface: '#FFFFFF',
    surfaceSecondary: '#F1F5F9',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    success: '#10B981',
    successForeground: '#FFFFFF',
    info: '#3B82F6',
    infoForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
    divider: '#E2E8F0',
    disabled: '#CBD5E1',
    disabledForeground: '#94A3B8',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    textTertiary: '#94A3B8',
    textDisabled: '#CBD5E1',
    tabBar: '#FFFFFF',
    header: '#0F172A',
    headerForeground: '#FFFFFF',
    aiGradientStart: '#7C3AED',
    aiGradientEnd: '#EC4899',
    primaryGradientStart: '#2563EB',
    primaryGradientEnd: '#60A5FA',
    starActive: '#F59E0B',
    overlay: 'rgba(0,0,0,0.5)',
    white: '#FFFFFF',
    black: '#000000',
  },
  dark: {
    text: '#F8FAFC',
    tint: '#60A5FA',
    background: '#020617',
    foreground: '#F8FAFC',
    card: '#0F172A',
    cardForeground: '#F8FAFC',
    primary: '#3B82F6',
    primaryDark: '#2563EB',
    primaryLight: '#93C5FD',
    primaryForeground: '#FFFFFF',
    secondary: '#1E293B',
    secondaryForeground: '#F8FAFC',
    accent: '#10B981',
    accentForeground: '#FFFFFF',
    muted: '#1E293B',
    mutedForeground: '#94A3B8',
    surface: '#0F172A',
    surfaceSecondary: '#1E293B',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    success: '#10B981',
    successForeground: '#FFFFFF',
    info: '#3B82F6',
    infoForeground: '#FFFFFF',
    border: '#1E293B',
    input: '#1E293B',
    divider: '#1E293B',
    disabled: '#334155',
    disabledForeground: '#64748B',
    textPrimary: '#F8FAFC',
    textSecondary: '#94A3B8',
    textTertiary: '#64748B',
    textDisabled: '#334155',
    tabBar: '#0F172A',
    header: '#0F172A',
    headerForeground: '#FFFFFF',
    aiGradientStart: '#7C3AED',
    aiGradientEnd: '#EC4899',
    primaryGradientStart: '#2563EB',
    primaryGradientEnd: '#60A5FA',
    starActive: '#F59E0B',
    overlay: 'rgba(0,0,0,0.7)',
    white: '#FFFFFF',
    black: '#000000',
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 100,
    button: 16,
    card: 20,
    input: 16,
    chip: 24,
    fab: 28,
    sheet: 32,
  },
};

export type ColorPalette = typeof colors.light & { radius: typeof colors.radius };

/** Static light palette for legacy StyleSheet.create usage */
export const themeLight = colors.light;

export { colors };
export default colors;
