export const AuthRoutes = {
  Onboarding: 'Onboarding',
  Login: 'Login',
  Signup: 'Signup',
  OtpVerify: 'OtpVerify',
} as const;

export const CustomerTabRoutes = {
  Home: 'Home',
  Marketplace: 'Marketplace',
  Garage: 'Garage',
  Community: 'Community',
  Profile: 'Profile',
} as const;

export const CustomerStackRoutes = {
  CustomerTabs: 'CustomerTabs',
  Cart: 'Cart',
  Search: 'Search',
  Notifications: 'Notifications',
  ProductDetail: 'ProductDetail',
  VehicleDetail: 'VehicleDetail',
  AiAssistant: 'AiAssistant',
  DealerStore: 'DealerStore',
  ServiceDetail: 'ServiceDetail',
  DriveDetail: 'DriveDetail',
  MyOrders: 'MyOrders',
  OrderTracking: 'OrderTracking',
  Checkout: 'Checkout',
  Payment: 'Payment',
  ServiceBookingDateTime: 'ServiceBookingDateTime',
  ServiceBookingVehicle: 'ServiceBookingVehicle',
  ServiceBookingLocation: 'ServiceBookingLocation',
  ServiceBookingAddons: 'ServiceBookingAddons',
  ServiceBookingSummary: 'ServiceBookingSummary',
  ServiceBookingPayment: 'ServiceBookingPayment',
  ServiceBookingConfirmed: 'ServiceBookingConfirmed',
  ServiceBookingTracking: 'ServiceBookingTracking',
  BookingDetail: 'BookingDetail',
  CreateCommunityPost: 'CreateCommunityPost',
  AddVehicle: 'AddVehicle',
  GarageVehicleDetail: 'GarageVehicleDetail',
  ChatList: 'ChatList',
  Chat: 'Chat',
  CreateChat: 'CreateChat',
  CreateGroup: 'CreateGroup',
  GroupInfo: 'GroupInfo',
  DealerChat: 'DealerChat',
  AIChat: 'AIChat',
  SavedAddresses: 'SavedAddresses',
  Wishlist: 'Wishlist',
  PaymentMethods: 'PaymentMethods',
  PersonalInformation: 'PersonalInformation',
  Settings: 'Settings',
  BlockedAccounts: 'BlockedAccounts',
  ChangePassword: 'ChangePassword',
  CustomerNotificationSettings: 'CustomerNotificationSettings',
  TermsConditions: 'TermsConditions',
  AppPermissions: 'AppPermissions',
  CustomerHelpSupport: 'CustomerHelpSupport',
  DeleteAccount: 'DeleteAccount',
  AddAddressMethod: 'AddAddressMethod',
  AddLiveLocation: 'AddLiveLocation',
  ManualAddress: 'ManualAddress',
  OtpVerification: 'OtpVerification',
  OtpLoading: 'OtpLoading',
  OtpSuccess: 'OtpSuccess',
} as const;

export const DealerTabRoutes = {
  Dashboard: 'Dashboard',
  Inventory: 'Inventory',
  Orders: 'Orders',
  Drive: 'Drive',
  Profile: 'DealerProfile',
  Bank: 'DealerBank',
} as const;

export const DealerStackRoutes = {
  DealerTabs: 'DealerTabs',
  DealerType: 'DealerType',
  BusinessRegistration: 'BusinessRegistration',
  ProductForm: 'ProductForm',
  VehicleForm: 'VehicleForm',
  ServiceForm: 'ServiceForm',
  StoreSettings: 'StoreSettings',
  BankDetails: 'BankDetails',
  GSTInfo: 'GSTInfo',
  UPIAccounts: 'UPIAccounts',
  NotificationSettings: 'NotificationSettings',
  ServiceBookings: 'ServiceBookings',
  DealerBookingDetail: 'DealerBookingDetail',
  DealerOrderDetail: 'DealerOrderDetail',
  BusinessDetails: 'BusinessDetails',
  PrivacySecurity: 'PrivacySecurity',
  HelpSupport: 'HelpSupport',
  Analytics: 'Analytics',
  EditAccount: 'EditAccount',
} as const;

export const RootRoutes = {
  Auth: 'Auth',
  Customer: 'Customer',
  Dealer: 'Dealer',
} as const;
